"""One-shot: rewrite portfolio.json floors to the new chest/enemy structure."""

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
PATH = ROOT / "backend" / "app" / "data" / "portfolio.json"

data = json.loads(PATH.read_text(encoding="utf-8"))

data["floors"] = [
    {
        "id": 0,
        "slug": "entrance",
        "name": "Entrance",
        "theme": "The mouth of the dungeon. A cold stone portal hums.",
        "palette": ["#0e0e12", "#1a1c2c", "#3e3546", "#b13e53", "#ffcd75"],
        "ambient": "Wind whistles. Portal hums.",
        "width": 18,
        "height": 12,
        "spawn": [3, 8],
        "exits": [],
        "interactables": [
            {
                "id": "entrance-portal",
                "kind": "portal_entrance",
                "x": 13,
                "y": 4,
                "w": 2,
                "h": 3,
                "label": "Dungeon Portal",
                "title": "STEP INTO THE DUNGEON",
                "body": "Ancient runes flicker. Step into the portal.",
                "accent": "#b13e53",
                "meta": {"to_floor": 1},
            }
        ],
        "soft_gate_required": [],
    },
    {
        "id": 1,
        "slug": "education",
        "name": "Education",
        "theme": "Dust. Broken desks. Rows of study halls.",
        "palette": ["#1a1c2c", "#29366f", "#41a6f6", "#a7f070", "#ffcd75"],
        "ambient": "Pages turning. Humming ancient wiring.",
        "width": 26,
        "height": 14,
        "spawn": [3, 7],
        "exits": [],
        "interactables": [
            {
                "id": "chest-kk",
                "kind": "chest",
                "x": 7,
                "y": 4,
                "w": 1,
                "h": 1,
                "label": "Chest - IT Cert",
                "title": "KOLEJ KOMUNITI - IT CERTIFICATE",
                "body": "Where the adventure began. IT fundamentals - hardware, networking, software.",
                "accent": "#ffcd75",
            },
            {
                "id": "chest-python",
                "kind": "chest",
                "x": 13,
                "y": 4,
                "w": 1,
                "h": 1,
                "label": "Chest - Python Bootcamp",
                "title": "PYTHON BOOTCAMP",
                "body": "Intensive Python - syntax, patterns, automation, scripting, package ecosystem.",
                "accent": "#a7f070",
            },
            {
                "id": "chest-gamuda",
                "kind": "chest",
                "x": 19,
                "y": 4,
                "w": 1,
                "h": 1,
                "label": "Chest - Gamuda AI",
                "title": "GAMUDA AI ACADEMY - FULL STACK AI ENGINEER",
                "body": "Python, FastAPI, React, Langchain, AI agents. Presented prototype to Minister YB Chang Lih Kang.",
                "accent": "#41a6f6",
            },
            {
                "id": "enemy-slime-1",
                "kind": "enemy",
                "x": 9,
                "y": 9,
                "w": 1,
                "h": 1,
                "label": "Dust Slime",
                "title": "",
                "body": "",
                "accent": "#a7f070",
                "meta": {"hp": 2, "speed": 32, "damage": 1, "species": "slime"},
            },
            {
                "id": "enemy-slime-2",
                "kind": "enemy",
                "x": 17,
                "y": 9,
                "w": 1,
                "h": 1,
                "label": "Dust Slime",
                "title": "",
                "body": "",
                "accent": "#a7f070",
                "meta": {"hp": 2, "speed": 32, "damage": 1, "species": "slime"},
            },
            {
                "id": "portal-edu-to-exp",
                "kind": "portal_locked",
                "x": 23,
                "y": 6,
                "w": 1,
                "h": 2,
                "label": "Portal - Work Experience",
                "title": "Portal Sealed",
                "body": "Loot all three chests to break the seal.",
                "accent": "#b13e53",
                "meta": {"to_floor": 2},
            },
        ],
        "soft_gate_required": ["chest-kk", "chest-python", "chest-gamuda"],
    },
    {
        "id": 2,
        "slug": "experience",
        "name": "Work Experience",
        "theme": "Old studio. Cameras. Screens flicker with engagement graphs.",
        "palette": ["#0e0e12", "#29366f", "#b13e53", "#b55088", "#fee761"],
        "ambient": "Muffled studio noise. Distant applause.",
        "width": 22,
        "height": 14,
        "spawn": [2, 10],
        "exits": [],
        "interactables": [
            {
                "id": "chest-hygr",
                "kind": "chest",
                "x": 11,
                "y": 5,
                "w": 1,
                "h": 1,
                "label": "Chest - HYGR",
                "title": "HYGR - CONTENT CREATOR / CAMPAIGNS",
                "body": "Natural Deodorant campaigns - voice, pacing, editing engineered for the algorithm. 38M+ views across platforms.",
                "accent": "#b13e53",
            },
            {
                "id": "enemy-ghost-1",
                "kind": "enemy",
                "x": 8,
                "y": 8,
                "w": 1,
                "h": 1,
                "label": "Screen Ghost",
                "title": "",
                "body": "",
                "accent": "#b55088",
                "meta": {"hp": 3, "speed": 40, "damage": 1, "species": "ghost"},
            },
            {
                "id": "enemy-ghost-2",
                "kind": "enemy",
                "x": 15,
                "y": 8,
                "w": 1,
                "h": 1,
                "label": "Screen Ghost",
                "title": "",
                "body": "",
                "accent": "#b55088",
                "meta": {"hp": 3, "speed": 40, "damage": 1, "species": "ghost"},
            },
            {
                "id": "portal-exp-to-agency",
                "kind": "portal_locked",
                "x": 20,
                "y": 6,
                "w": 1,
                "h": 2,
                "label": "Portal - Orion",
                "title": "Portal Sealed",
                "body": "Loot the HYGR chest to break the seal.",
                "accent": "#b13e53",
                "meta": {"to_floor": 3},
            },
        ],
        "soft_gate_required": ["chest-hygr"],
    },
    {
        "id": 3,
        "slug": "agency",
        "name": "Orion Automation",
        "theme": "The throne of the dungeon. Gold runes. The final floor.",
        "palette": ["#1a1c2c", "#29366f", "#b13e53", "#fee761", "#f4f0bc"],
        "ambient": "Golden hum. Runes breathing.",
        "width": 22,
        "height": 14,
        "spawn": [2, 11],
        "exits": [],
        "interactables": [
            {
                "id": "chest-orion",
                "kind": "chest",
                "x": 10,
                "y": 5,
                "w": 1,
                "h": 1,
                "label": "Chest - Orion Automation",
                "title": "ORION AUTOMATION - MY AGENCY",
                "body": "Running my own agency - Custom Automation, Website Workflows, Chatbots, Marketing SEO/AEO/GEO. SSM-registered in Shah Alam/Selangor.",
                "accent": "#fee761",
            },
            {
                "id": "enemy-boss",
                "kind": "enemy",
                "x": 14,
                "y": 6,
                "w": 1,
                "h": 1,
                "label": "Shadow Lord",
                "title": "",
                "body": "",
                "accent": "#b13e53",
                "meta": {"hp": 5, "speed": 28, "damage": 1, "species": "boss"},
            },
            {
                "id": "chest-contact",
                "kind": "chest_contact",
                "x": 17,
                "y": 5,
                "w": 1,
                "h": 1,
                "label": "Crystal Chest - Contact",
                "title": "SEND A MESSAGE",
                "body": "A Crystal Chest. Peer inside to reach Varakorn directly.",
                "accent": "#41a6f6",
            },
        ],
        "soft_gate_required": ["chest-orion"],
    },
]

PATH.write_text(json.dumps(data, indent=2, ensure_ascii=False), encoding="utf-8")
print(f"wrote {len(data['floors'])} floors")
